when:
  - event: [push, manual]
    branch: [main, ci]
  - event: [manual]
    evaluate: 'DOC == "true"'
labels:
  name: jp35

steps:
- name: build
  image: node:18.20.7-alpine3.21
  commands:
  - apk add --no-cache git
  - corepack enable
  - corepack prepare pnpm@latest --activate
  - ls -la
  - pnpm install
  - pnpm run build
  - ls -la .vitepress/dist
  - rm -rf /landscape/*
  - mv .vitepress/dist/* /landscape/
  - ls -la /landscape
  volumes:
  - /d/landscape/html:/landscape
  - /d/agent_cache/pnpm-store:/root/.pnpm-store
